### ISSUE TITLE
Discussion for us

### ISSUE THREAD

**Issue by LeeMing0619** [Bartis1313/csgo#74]
Hi,
How are you?
I have one job for you, if you are available, please contact me.
skype: leeming0619

Thanks regards.

**Comment by Bartis1313** [comment]
last time I used skype was many years ago. And if it's about p2c forget about it

**Comment by LeeMing0619** [comment]
> last time I used skype was many years ago. And if it's about p2c forget about it

Can you share your email address?

**Comment by recoil23** [comment]
I am also interested in your discord regarding constuctor you found for weather feature. I want to make it rain like sharklaser did it. Can you share some advice please

**Comment by Bartis1313** [comment]
Bartis#3611

**Comment by Bartis1313** [comment]
I tried to mess with that. Constructor is completely not needed to call directly, because it gets called on creation of that class, and that object gets pushed into the precip list. So far so good, but not really. That's because server is responsible for that, and server is responsible to tell the client what data to load for physics. I am talking about the provided collide for rain particles.
I don't know how to provide valid collide data from client myself, hence why I left code commented in those parts.
