### ISSUE TITLE
code is shit

### ISSUE THREAD

**Issue by JukoiDev** [Bartis1313/csgo#78]
this code is fucking shit. i found this project 3 minutes ago and i already saw notorious use of "lenght" instead of "length" and this:
https://github.com/Bartis1313/csgo/blob/master/hack/cheats/features/visuals/world/tone.cpp#L54-L58

gj on glow tho, it's actually quite good and also gj for using modern c++(std::ranges::sort and views::iota)

**Comment by JukoiDev** [comment]
and also inconsistent naming conventions i.e. aimbot.cpp:
`cfgWeapon` and `weapon_recoil_scale`

**Comment by Bartis1313** [comment]
If you are able to not make it shit you are welcome. Nobody ever said that the code is for the purest clean code ever.
For info: ``cfgWeapon`` is not a cvar anyhow. And ``weapon_recoil_scale`` is.
"lenght" is a typo.
You are welcomed to make a PR instead of pointing someone "your code shit".
Thank you anyway. I will go through comments, and vars again to remove those typos.

**Comment by Bartis1313** [comment]
Done, thank you.
PS: didn't really go through all comments, typos happen and user will still get the reference.
